---
samba_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63633338646331646264326531323762656664346332343766616266306265363631373766333461
          6334353561613364333431653132633666663831373764620a306461656432303862393762646164
          65386531643764636433346662376365393461613864363436643537313738343634383166376161
          6564366566306639320a613163343535316235653364663861663835646566633565386238646166
          3662

samba_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65363430323262343461396262366531376663346239636363656230323330323264356635313561
          6261613365343065303462613634303539333133316432310a633437336638323039663964383465
          30303361366162323963343639636335383061323634646332353762323335383366346663643233
          6430323865633965640a386339316566323637333530376164343431316430316232623434366133
          64396465633237373435356536643331313430373362313535643532343465356439
